### ISSUE TITLE
Create issues for each feature

### ISSUE THREAD

**Issue by alexlafroscia** [gothinkster/ember-realworld#1]
_From @Alonski on April 23, 2017 7:12_

Need to create issues for all the features that need to be in this to comply with the realworld.

_Copied from original issue: Alonski/realworld-ember#1_

**Comment by alexlafroscia** [comment]
Definitely on board! I'll try to go through the list of tasks and see what I can itemize

**Comment by alexlafroscia** [comment]
_From @brwr on April 26, 2017 15:10_

Hey! Just popping over from [gothinkster/realworld](https://github.com/gothinkster/realworld/).

I think this is a really good idea! Gonna talk to @EricSimons about recommending all projects start by creating a Github Project that lists out the features they need to work on. This is also very helpful for us because we can see how far along each project is.

Any progress on this front? Anything we can do to help?

**Comment by alexlafroscia** [comment]
_From @Alonski on April 26, 2017 17:0_

I wanted to create a GitHub project listing all the requirements just haven't gotten around to it.
Making slow progress. With work and school barely have time 😄

**Comment by alexlafroscia** [comment]
_From @brwr on April 26, 2017 17:6_

No worries! Believe me, I know what you mean. :smile:

Why don't you hop in the realworld Gitter channel? http://gitter.im/realworld/main

I'd love to chat and learn more about what we can do to help you as a project creator/maintainer.

**Comment by alexlafroscia** [comment]
I think at this point, we have at least the basic needs scaffolded out. It's hard to itemize everything up front, but I think it's a good start.

**Comment by Alonski** [comment]
We did it! We are finally offical!
