### ISSUE TITLE
Should we migrate this app to become an Ember Octane app?

### ISSUE THREAD

**Issue by patocallaghan** [gothinkster/ember-realworld#100]
Follow-up issue to https://github.com/gothinkster/ember-realworld/pull/99 to allow us to discuss without having to focus on the code changes.

Originally it was discussed that Ember Realworld would show how to build a Ember Classic application. A new separate app was then spun up which outlined how to build the RealWorld app using Ember Octane.

But it has since been suggested that these Ember apps should not be separate and should just be merged into this Ember RealWorld app. The thinking is that Ember Octane is not a separate framework but rather just an updating of syntax and the programming model.

Conversation from Discord below:
![image](https://user-images.githubusercontent.com/685034/80321792-e7a1fe00-8817-11ea-9669-50cc8ec0c44d.png)
![image](https://user-images.githubusercontent.com/685034/80321795-ed97df00-8817-11ea-9cb8-bd4c46c39365.png)
![image](https://user-images.githubusercontent.com/685034/80321798-f2f52980-8817-11ea-81d7-72329866b588.png)

/cc @mansona @Alonski @GCheung55 @trek

**Comment by Alonski** [comment]
@patocallaghan @mansona I say we just do it!

**Comment by patocallaghan** [comment]
@Alonski We can close this now 😁
