### ISSUE TITLE
Enable CI?

### ISSUE THREAD

**Issue by patocallaghan** [gothinkster/ember-realworld#113]
@Alonski I noticed in https://github.com/gothinkster/ember-realworld/pull/112 that we don't have CI enabled. We had a linting error but the status checks were 🟢

![image](https://user-images.githubusercontent.com/685034/96729810-764d9d00-13ad-11eb-9915-ffeada070576.png)

Any chance you could enable it please or is that something I can do?

**Comment by Alonski** [comment]
@patocallaghan Sorry for missing this.
Maybe we should migrate to GH Actions?

**Comment by ijlee2** [comment]
I can help with writing a GitHub Actions workflow. Is it just the `lint` and `test` scripts that need to be run? I don't see anything else in `travis.yml` that would cause the workflow to be complex.

**Comment by Alonski** [comment]
@ijlee2 I think so. That is pretty much what we need. Worst case we can update it later. Thanks!

**Comment by ijlee2** [comment]
@Alonski https://github.com/gothinkster/ember-realworld/pull/117 is ready for review. If you have questions, feel free to leave a comment.
