### ISSUE TITLE
Configure Mirage for mocking the API during tests

### ISSUE THREAD

**Issue by alexlafroscia** [gothinkster/ember-realworld#2]
_From @alexlafroscia on April 23, 2017 22:0_

Since it would be great to have a solid test suite here, we should mock out the API using Mirage.  The API is pretty simple so this should be a good task for someone that's looking for some low-hanging fruit.

_Copied from original issue: Alonski/realworld-ember#8_

**Comment by GCheung55** [comment]
Having completed the project (Ember Realworld is a part of Realworld now!) all, if not most, of the APIs should have been mocked. We should do a quick audit or close this ticket if it's no longer relevant.
