### ISSUE TITLE
[Nav] Logo link to homepage

### ISSUE THREAD

**Issue by patocallaghan** [gothinkster/ember-realworld#41]
Currently the logo in the top left is linking to index.html.

It should be converted to a `link-to` and link to 'home'. The link should also set the default query params, i.e. tag=null, page=1 etc

**Comment by patocallaghan** [comment]
Closed in #43

**Comment by Alonski** [comment]
@patocallaghan This wasn't fixed :)

**Comment by patocallaghan** [comment]
@Alonski 🤦‍♂ I saw the `home` link-to a few lines after that so assumed it was that
