### ISSUE TITLE
[Nav] Componentize the top nav

### ISSUE THREAD

**Issue by patocallaghan** [gothinkster/ember-realworld#43]
Currently we use lots of controllers + templates but we should defer to use components where we can.

We should componentize the top-nav to be a component rather have it directly in the template.

Example from the Octane repo: https://github.com/patocallaghan/realworld-starter-kit/blob/master/app/templates/components/nav.hbs

Wanna write some tests:
* Component integration test: Logged in vs logged out state

### Logged out
![image](https://user-images.githubusercontent.com/685034/57111368-bfcaa800-6d33-11e9-9607-69454578f9d4.png)

### Logged in
![image](https://user-images.githubusercontent.com/685034/57111337-a9245100-6d33-11e9-8ea6-e52460f8d268.png)

**Comment by delusioninabox** [comment]
🖐 And also this one. :)

**Comment by patocallaghan** [comment]
Heads up @delusioninabox. @jonnii implemented this in #72
