### ISSUE TITLE
[Footer] Componentize the footer

### ISSUE THREAD

**Issue by patocallaghan** [gothinkster/ember-realworld#44]
Currently we use lots of controllers + templates but we should defer to use components where we can.

We should componentize the footer to be a component rather have it directly in the template.

Example from the Octane repo: https://github.com/patocallaghan/realworld-starter-kit/blob/master/app/templates/components/footer.hbs

### Footer
![image](https://user-images.githubusercontent.com/685034/57111470-1932d700-6d34-11e9-868a-ed12a700901f.png)

**Comment by delusioninabox** [comment]
🤚 I'll take this one!
