### ISSUE TITLE
Question: Can we turn off Mirage for local development?

### ISSUE THREAD

**Issue by patocallaghan** [gothinkster/ember-realworld#47]
While I understand the value-add of Mirage in the development environment, especially when APIs are not built, in my opinion we don't really need it here. The API provided by gothinkster is feature-complete and I've never had any issues with it in development.

I find in my own development in this repo I'm always disabling it but reverting that change before committing.

Upsides:
* gothinkster API is feature complete
* Working against a live API so we won't miss anything in our mocks

Downsides:
* Can't develop if network is down
* We need to create the mocks anyway for testing

I'd be interested in hearing your thoughts. 

/cc @Alonski @delusioninabox @mansona

**Comment by mansona** [comment]
Personally I think it should be turned off for local development. None of the other Realworld examples have anything like mirage so it seems odd that if someone was comparing implementations they would see such a stark difference 

I'm curious to know how many other Realworld examples even have tests 🤔 and if they even bother with mocking or just hit the API. I'm not suggesting that we remove mirage I'm just trying to understand the problem space

**Comment by patocallaghan** [comment]
@mansona the barrier to entry re:tests is extremely low.

From the their [README.md](https://github.com/gothinkster/realworld/tree/master/spec#to-write-tests-or-to-not-write-tests)

> we require a minimum of one unit test with every repo, but we'd definitely prefer all of them to include excellent testing coverage if the maintainers are willing to add it (or if someone in the community is kind enough to make a pull request :)

Just look at the top 3 frontend implementations:

1. React - doesn't appear to have tests 🤔 
2. Angular - has two test files of a trivial test each (live api)
3. Elm - has a single test file (looks like it's mocked)

While we don't _need_ to write tests I think we should in some form or another. Although according to @Alonski we can't hook it up to CI 😭

**Comment by patocallaghan** [comment]
I should also add we need Mirage in testing. You can't do accurate testing using the live API as responses will change and you can't guarantee consistency.

**Comment by Alonski** [comment]
I am OK with not using Mirage for local development. We did it when we were starting out because it felt the "Embery" thing to do. Mirage is great and I feel we definitely want to keep it for tests (which we need more of)

Also I have been working with the `gothinkster` people to try and get CI working again :)

**Comment by patocallaghan** [comment]
Great stuff @Alonski. I'll put together a PR later to turn it off in development 👍

Nice work on CI too 🎉
