### ISSUE TITLE
Separate concerns of the main user model

### ISSUE THREAD

**Issue by patocallaghan** [gothinkster/ember-realworld#49]
I'd like to propose that we split the main user model into two models: `user` and `profile`. They are very similar but serve two subtly different roles.

* `user` - The current user. Can be used to tell if a user is logged in or not. Can be used on the settings page to edit a user's properties. Can grab the logged in user's article feed.
* `profile` - Similar to a user but more to do with authors of articles. They can be followed, have their articles favorited/unfavorited. 

My reasoning? While I initially tried to use the same model in the Octane version of the app, this abstraction broke down when I needed use the same model between the settings page and article list/profile pages. (Octane repo: [Profile](https://github.com/patocallaghan/realworld-starter-kit/blob/master/app/models/profile.js), [User](https://github.com/patocallaghan/realworld-starter-kit/blob/master/app/models/user.js))

The `profile` model has the username as the primary key for identifying a user, they have no other unique identifier.

But then when editing the user we need to be able to edit the user's username. This is not possible as we are trying to treat this property as the primary key for the `profile`. Also the `/user` endpoint returns a unique integer identifier as well as the username.

Here are some sample payload responses from the API.

```json
// User
{
  "user": {
    "id": 52999,
    "email": "some@username.com",
    "createdAt": "2019-03-31T00:15:23.573Z",
    "updatedAt": "2019-04-05T07:25:08.330Z",
    "username": "someusername",
    "bio": null,
    "image": "https://s3.amazonaws.com/uifaces/faces/twitter/yoyoyo/128.jpg",
    "token": "eyJ0eXAiOiJKV1..........."
  }
}

// Profile
{
  "username": "lifelonglearner123",
  "bio": null,
  "image": "https://static.productionready.io/images/wat-yo.jpg",
  "following": false
}
```

What do you folks think?

/cc @Alonski @mansona

**Comment by Alonski** [comment]
I'm on my phone but I remember having one model and the settings page worked correctly as well as the posts. Need to look at the closed PR. Either way if this makes sense to you I'm not against it. Will they inherit from one another or from a base class? Is a user a profile or the other way around?

**Comment by patocallaghan** [comment]
Thanks @Alonski. I'd be interested in seeing that PR, I had a look in the closed PRs and didn't see anything there. How did it handle the fact that we can edit the primary key, i.e. the user's name?

In my mind I wouldn't have a base class and just separate them completely. In my mind the complexity of inheritance isn't worth it here for such a small overlap in properties.

```js
// profile
export default DS.Model.extend({
  // id is implicitly the user's name
  bio: DS.attr('string'),
  image: DS.attr('string'),
  following: DS.attr('boolean'),
});

// user
export default DS.Model.extend({
  // These are the only two attrs which are shared between both models
  bio: DS.attr('string'),
  image: DS.attr('string'),

  email: DS.attr('string'),
  password: DS.attr('string'),
  token: DS.attr('string'),
  username: DS.attr('string'), // username is a regular `attr` here so we can update it without an weirdness
  createdAt: DS.attr('string'),
  updatedAt: DS.attr('string'),
});
```

**Comment by mansona** [comment]
@patocallaghan I think this is a good way to go forward. Every time I have tried to implement this sort of a thing it always tends to be simpler to work with when you have a separate Profile and User object.

I don't know if @Alonski your response was in the affirmative but I am a strong 👍 on taking this approach.

**Comment by patocallaghan** [comment]
Thanks @mansona, that’s all the validation I need. I’ll go ahead and put together a PR. Thanks 👍

**Comment by jonnii** [comment]
Once this is done I'll do the follow/unfollow button.

**Comment by patocallaghan** [comment]
Great @jonnii. I've got a WIP PR which I'm hoping to ship soon 👍
