### ISSUE TITLE
[Profile page] Favorite/unfavorite article

### ISSUE THREAD

**Issue by patocallaghan** [gothinkster/ember-realworld#51]
On an author's profile page we should be able to favorite/unfavorite articles

This should just start working when this is made to work in https://github.com/gothinkster/ember-realworld/issues/46 from the homepage.

But worth calling out to verify that is actually the case

**Comment by GCheung55** [comment]
It's buggy - favorite/unfavorite works but removes all the other articles listed.

**Comment by GCheung55** [comment]
Closing, fixed in #86.
