### ISSUE TITLE
[Profile page] Follow/unfollow profile

### ISSUE THREAD

**Issue by patocallaghan** [gothinkster/ember-realworld#52]
We should able to follow/unfollow a user's profile

![image](https://user-images.githubusercontent.com/685034/57197566-c427d880-6f60-11e9-850b-65e3103b8874.png)

### Features
* Unfollowed state
![image](https://user-images.githubusercontent.com/685034/57197786-75c80900-6f63-11e9-91de-d670c52afd5c.png)

* Followed state
![image](https://user-images.githubusercontent.com/685034/57197598-49ab8880-6f61-11e9-8c5f-3502deca9993.png)

---
#### Follow user
POST /api/profiles/:username/follow

Authentication required, returns a Profile

No additional parameters required

#### Unfollow user
DELETE /api/profiles/:username/follow

Authentication required, returns a Profile

No additional parameters required
---

### Tests
* Integration - Initial follow/unfollowed state
* Integration - Follow profile and state should change
* Integration - Unfollow profile and state should change

**Comment by GCheung55** [comment]
Closing, fixed in #86.
