### ISSUE TITLE
[Article form] Title, description, post, tags

### ISSUE THREAD

**Issue by patocallaghan** [gothinkster/ember-realworld#64]
#### Features
* Component with form fields and submit button
* Title, description, content (markdown), tags
* Form should work in two scenarios
  * article model passed in i.e. editing an existing article
  * no article passed in, create record on init if none passed in, i.e. new article
* Tag list can be entered as a space separated list
* Form should appear on the "New article"  and "Edit article" pages

![image](https://user-images.githubusercontent.com/685034/57234976-c39f4880-7019-11e9-8d0c-b74efcd82071.png)

**Comment by GCheung55** [comment]
> * Tag list can be entered as a space separated list

The demo, demo.realworld.io, doesn't support this. Entering a space separated list will create a single tag with all the words.

**Comment by patocallaghan** [comment]
@GCheung55 Interesting. One of the demos had it like that (can't remember which) but just make it a comma-separated list in that case.
