### ISSUE TITLE
Create follow-user-button component

### ISSUE THREAD

**Issue by GCheung55** [gothinkster/ember-realworld#89]
Current follow/unfollow buttons are not components so there’s a bit of duplication.

**Comment by johpol** [comment]
I can take a look at this

**Comment by GCheung55** [comment]
@johpol I appreciate it. Please take a look at how `[favorite-article-button](https://github.com/gothinkster/ember-realworld/blob/master/app/components/favorite-article-button.js)` was implemented as a reference.

**Comment by GCheung55** [comment]
Fixed in #92
